- fr/entretien.md
Updating maintenance page for Release 1.3.63 in CATE and Prod Certificate Update
> April 14 Maintenance-fr

- en/maintenance.md
Updating maintenance page for Release 1.3.63 in CATE and Prod Certificate Update
> April 14 Maintenance-en

- en/maintenance.md
Updating maintenance page to reflect release 1.3.63 deployment to Production
> April 23 Maintenance-en

- fr/entretien.md
Updating maintenance page to reflect release 1.3.63 deployment to Production
> April 23 Maintenance-fr

- en/maintenance.md
Updating maintenance page for 1.4.44 English page
> June 7 - Maintenance – 1.4.44 – English

- fr/entretien.md
Updating maintenance page for 1.4.44 French page
> June 7 - Maintenance – 1.4.44 – French

- _includes/platform-footer.html
- en/help/index.md
- en/privacy/index.md
- fr/aide/index.md
- fr/confidentialite/index.md
- Fixed some accessibility issues
- Added missing content
- Fixed some bolding errors
> Content updates to help and privacy pages

- fr/entretien.md
Update maintenance page for CATE 1.4.48 release in french
> June 14 - Maintenance – 1.4.48 – French

- en/maintenance.md
Update maintenance page for CATE 1.4.48 release in english
> June 14 - Maintenance – 1.4.48 – English

- fr/entretien.md
Update maintenance page for 1.4.48 - French page
> Maintenance - 1.4.48 - French

- fr/entretien.md
Update maintenance page for 1.4.62 release in French
> July 13 - Maintenance - 1.4.62 - French

- en/maintenance.md
Update maintenance page for 1.4.62 release in English
> July 13 - Maintenance - 1.4.62 - English

- fr/entretien.md
July 19 maintenance update to refer to CATE continuous release pipeline testing
> July 19 - Maintenance Update – French

- en/maintenance.md
July 19 maintenance update to refer to CATE continuous release pipeline testing
> July 19 - Maintenance Update – English

- en/index.html
Missed updating the text for index main page
> Update index.html to include text on Announcements - EN

- fr/annonce.md
- fr/index.html
Fixed typos and annonce.html redirect from main page
> Updating index.html with Annonces and fixed typo on Annonce html

- en/index.html
Changed the Announcements helper text to "Check out" instead of hear
> Update index.html - Updated to use "Check out"

- fr/annonce.md
Updated new french text for GIAC -> ICGA and added messaging regarding the release of SSC's MFAaaS 3.0 impact on Sign In Canada clients
> August 8 - Announcement - French

- fr/entretien.md
Updating maintenance page for 1.4.93 release
> Sept 7 - Maintenance - 1.4.93 - French

- en/maintenance.md
Updating maintenance page for 1.4.93 release
> Sept 7 - Maintenance - 1.4.93 - English

- en/maintenance.md
October 14 - TBS Network Maintenance – English
> October 14 - TBS Network Maintenance – English

- fr/entretien.md
October 14 - TBS Network Maintenance – French
> October 14 - TBS Network Maintenance – French

- en/maintenance.md
Updating maintenance page for TBS network patching to indicate outage on Oct 25
> Oct 24 - Maintenance - Network outage - English

- fr/entretien.md
Updating maintenance page for TBS network patching to indicate outage on Oct 25
> Oct 24 - Maintenance - Network outage - French

- fr/annonce.md
Updated subject title and removed wording on vendor updates
> February 14 - Announcement Update - French

- .github/workflows/build-jeckyll.yml
Update build-jeckyll.yml - updated checkout action to v3
`actions/checkout@v2`
> Update build-jeckyll.yml - up dated checkout action to v3

- .github/workflows/build-jeckyll.yml
> Update build-jeckyll.yml updated cache to v3

- .github/workflows/build-jeckyll.yml
Updated to checkout and cache to v4
> Update build-jeckyll.yml - updated to v4

- .github/workflows/build-jeckyll.yml
jeffreytse/jekyll-deploy-action@v0.5.1
checkout@v3
cache@v3
> Update build-jeckyll.yml - updated jekyll-deploy-action v0.5.1

- .github/workflows/build-jeckyll.yml
referencing ruby setup in:
https://github.com/actions/starter-workflows/blob/main/pages/jekyll.yml
> Update build-jeckyll.yml - setup ruby

- en/maintenance.md
Updating the English maintenance page to notify of the potential outage from the TLS certificate replacement in Prod
> July 25 - Maintenance - English

- fr/entretien.md
Updating TLS certificate for auth.id.canada.ca with IMTD for F5 and keyvault.
This task would require restarting of the gluu container to take the new certificate
> July 25 - Maintenance - FR

- en/maintenance.md
Update the SIC website maintenance page for the Production UMA private key rotation.
> Private Key Rotation - English

- fr/entretien.md
Update the SIC website maintenance page for the Production UMA private key rotation.
> Private Key Rotation - French
